/**
 * AiAssistant — floating Operations Intelligence Assistant for the HJ Admin Portal.
 *
 * Rendered once in Layout so it is available on every admin screen. Surfaces a
 * live rule-based briefing (KPIs, alerts, insights, quick actions) generated by
 * the backend, plus a command bar that resolves short queries into actionable
 * replies with deep links.
 */

import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../api';
import { hasPermission } from '../../utils/adminPermissions';
import './AiAssistant.css';

/* ── Types ────────────────────────────────────────────────────── */

interface Kpi { label: string; value: string; icon: string; tone: string; }
interface Alert { severity: string; title: string; message: string; route: string; permission: string; }
interface Insight { tone: string; title: string; message: string; }
interface Action { label: string; route: string; icon: string; permission: string; }

interface Briefing {
  greeting: string;
  adminName: string;
  generatedAt: string;
  kpis: Kpi[];
  alerts: Alert[];
  insights: Insight[];
  actions: Action[];
}

interface AssistantReply {
  intent: string;
  title: string;
  summary: string;
  bullets: string[];
  route: string | null;
  permission: string | null;
}

const REFRESH_MS = 60_000;

const SUGGESTIONS = ['kyc queue', 'goals', 'schedule tomorrow', 'complaints', 'demand forecast', 'notification studio'];

const severityIcon: Record<string, string> = {
  critical: '🚨',
  high: '🛡️',
  medium: '⚠️',
  low: 'ℹ️',
};

/* ── Component ────────────────────────────────────────────────── */

export default function AiAssistant() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [loading, setLoading] = useState(true);
  const [reply, setReply] = useState<AssistantReply | null>(null);
  const [query, setQuery] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const can = (permission?: string | null) =>
    !permission || hasPermission(permission as Parameters<typeof hasPermission>[0]);

  const fetchBriefing = async () => {
    try {
      const res = await api.get<Briefing>('/assistant/briefing');
      setBriefing(res.data);
    } catch {
      // silent — widget stays collapsed/empty rather than breaking the shell
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBriefing();
    intervalRef.current = setInterval(fetchBriefing, REFRESH_MS);
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, []);

  const go = (route: string) => {
    navigate(route);
    setOpen(false);
  };

  const submitQuery = async (e: React.FormEvent) => {
    e.preventDefault();
    const q = query.trim();
    if (!q || submitting) return;
    setSubmitting(true);
    setReply(null);
    try {
      const res = await api.post<AssistantReply>('/assistant/query', { query: q });
      setReply(res.data);
    } catch {
      setReply({ intent: 'ERROR', title: 'Sorry, something went wrong', summary: 'I could not reach the operations engine. Try again in a moment.', bullets: [], route: null, permission: null });
    } finally {
      setSubmitting(false);
    }
  };

  const alertCount = briefing ? briefing.alerts.filter((a) => can(a.permission)).length : 0;

  return (
    <>
      {/* ── Floating Action Button ─────────────────── */}
      <button
        className={`ai-assistant-fab${open ? ' ai-assistant-fab--active' : ''}`}
        onClick={() => setOpen(!open)}
        aria-label="Toggle AI Operations Assistant"
        title="HJ AI Operations Assistant"
      >
        <span className="ai-assistant-fab__icon">🤖</span>
        {alertCount > 0 && (
          <span className="ai-assistant-fab__badge">{alertCount}</span>
        )}
        {!open && (
          <span className="ai-assistant-fab__label">AI Assistant</span>
        )}
      </button>

      {/* ── Panel ──────────────────────────────────── */}
      {open && (
        <div className="ai-assistant">
          {/* Header */}
          <div className="ai-assistant__header">
            <div className="ai-assistant__header-top">
              <span className="ai-assistant__header-icon">🤖</span>
              <div className="ai-assistant__header-title">
                <div className="ai-assistant__header-name">HJ AI Operations Assistant</div>
                <div className="ai-assistant__header-sub">
                  <span className="ai-assistant__live-dot" />
                  Live intelligence
                </div>
              </div>
              <button
                className="ai-assistant__close"
                onClick={() => setOpen(false)}
                aria-label="Close assistant"
              >
                ✕
              </button>
            </div>
            {briefing && (
              <div className="ai-assistant__greeting">
                {briefing.greeting}, {briefing.adminName} 👋
                <span className="ai-assistant__time"> · {briefing.generatedAt}</span>
              </div>
            )}
          </div>

          {/* Body */}
          <div className="ai-assistant__body">
            {loading && !briefing ? (
              <div className="ai-assistant__loading">
                <div className="ai-assistant__spinner" />
                <p>Reading platform data…</p>
              </div>
            ) : !briefing ? (
              <div className="ai-assistant__empty">
                <p>Assistant is unavailable right now.</p>
              </div>
            ) : (
              <>
                {/* KPIs */}
                <div className="ai-assistant__kpis">
                  {briefing.kpis.map((kpi) => (
                    <div className="ai-assistant__kpi" key={kpi.label}>
                      <span className="ai-assistant__kpi-icon">{kpi.icon}</span>
                      <span className={`ai-assistant__kpi-value ai-assistant__kpi-value--${kpi.tone}`}>
                        {kpi.value}
                      </span>
                      <span className="ai-assistant__kpi-label">{kpi.label}</span>
                    </div>
                  ))}
                </div>

                {/* Alerts */}
                {briefing.alerts.filter((a) => can(a.permission)).length > 0 && (
                  <div className="ai-assistant__section">
                    <div className="ai-assistant__section-title">Needs attention</div>
                    {briefing.alerts
                      .filter((a) => can(a.permission))
                      .map((alert) => (
                        <div className={`ai-alert ai-alert--${alert.severity}`} key={alert.title}>
                          <span className="ai-alert__icon">{severityIcon[alert.severity] || '⚠️'}</span>
                          <div className="ai-alert__content">
                            <div className="ai-alert__title">{alert.title}</div>
                            <div className="ai-alert__msg">{alert.message}</div>
                          </div>
                          <button className="ai-alert__open" onClick={() => go(alert.route)}>Open</button>
                        </div>
                      ))}
                  </div>
                )}

                {/* Insights */}
                {briefing.insights.length > 0 && (
                  <div className="ai-assistant__section">
                    <div className="ai-assistant__section-title">AI Insights</div>
                    {briefing.insights.map((insight) => (
                      <div className={`ai-insight ai-insight--${insight.tone}`} key={insight.title}>
                        <div className="ai-insight__title">{insight.title}</div>
                        <div className="ai-insight__msg">{insight.message}</div>
                      </div>
                    ))}
                  </div>
                )}

                {/* Query reply */}
                {reply && (
                  <div className="ai-assistant__section ai-assistant__reply">
                    <div className="ai-assistant__reply-title">{reply.title}</div>
                    <div className="ai-assistant__reply-summary">{reply.summary}</div>
                    {reply.bullets.length > 0 && (
                      <ul className="ai-assistant__reply-bullets">
                        {reply.bullets.map((b) => (
                          <li key={b}>{b}</li>
                        ))}
                      </ul>
                    )}
                    {reply.route && can(reply.permission) && (
                      <button className="ai-assistant__reply-open" onClick={() => go(reply.route as string)}>
                        Open page →
                      </button>
                    )}
                  </div>
                )}

                {/* Quick actions */}
                <div className="ai-assistant__section">
                  <div className="ai-assistant__section-title">Quick actions</div>
                  <div className="ai-assistant__actions">
                    {briefing.actions.filter((a) => can(a.permission)).map((action) => (
                      <button
                        className="ai-assistant__action"
                        key={action.label}
                        onClick={() => go(action.route)}
                      >
                        <span className="ai-assistant__action-icon">{action.icon}</span>
                        {action.label}
                      </button>
                    ))}
                  </div>
                </div>
              </>
            )}
          </div>

          {/* Command bar */}
          <form className="ai-assistant__footer" onSubmit={submitQuery}>
            <div className="ai-assistant__chips">
              {SUGGESTIONS.map((s) => (
                <button
                  key={s}
                  type="button"
                  className="ai-assistant__chip"
                  onClick={() => {
                    setQuery(s);
                    setReply(null);
                  }}
                >
                  {s}
                </button>
              ))}
            </div>
            <input
              className="ai-assistant__input"
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Ask me… e.g. kyc queue"
              disabled={submitting}
              aria-label="Ask the operations assistant"
            />
            <button
              className="ai-assistant__send"
              type="submit"
              disabled={submitting || !query.trim()}
              aria-label="Ask"
            >
              {submitting ? '…' : '➤'}
            </button>
          </form>
        </div>
      )}
    </>
  );
}
